# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import './custom_lane.rb'

setup_travis
scan(devices: ["iPhone 11"])
default_platform(:ios)

platform :ios do
  desc "My test lane"
  lane :custom_lane do
    custom_lane
  end
end
